name: Run Examples

on:
    pull_request:
        types: [labeled]

defaults:
    run:
        working-directory: examples

jobs:
    run-examples:
        if: github.event.label.name == 'Run examples'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'

            - name: Install dependencies
              uses: ramsey/composer-install@v3

            - name: Run OpenAI examples
              run: ./runner --filter=openai

            - name: Remove label
              uses: actions/github-script@v7
              with:
                  script: |
                      await github.rest.issues.removeLabel({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        name: 'Run examples'
                      });
